sudo: true
language: haskell

git:
  depth: 5

cabal: "head"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.6.3

  - ghc: 8.6.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --no-run-tests
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
       echo 'No tests'
    else
      stack build --system-ghc --test --bench --no-run-benchmarks --no-terminal --ghc-options=-Werror
    fi

  # HLint check
  - curl https://raw.githubusercontent.com/siapbantu/git-cuk/0d05809d08518d0b42dcdd176fad154d0be5ea97/.hlint.yaml -o .hlint-relude.yaml
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint -h .hlint-relude.yaml src/


notifications:
  email: false
